#ifndef REST_SERVER_CERT_H
#define REST_SERVER_CERT_H

static const char REST_SERVER_CERT_PEM[] = R"BOLTYREST(
-----BEGIN CERTIFICATE-----
MIIB3DCCAYKgAwIBAgIUJMVbAW9+2EFXBdU2kIA+vZoE73swCgYIKoZIzj0EAwIw
HTEbMBkGA1UEAwwSQm9sdHkgUkVTVCBSb290IENBMB4XDTI2MDQyMTExNTgwN1oX
DTM2MDQxODExNTgwN1owHDEaMBgGA1UEAwwRQm9sdHkgUkVTVCBTZXJ2ZXIwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAASPC/56S78kzNwsmsTu86nT0MWOq/Sx7hg1
RD7zhpU4z8WpeJ62QLPDPv93UqnkoNou6EyKMugSF/09xMJSWMQBo4GgMIGdMAwG
A1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMB
MCgGA1UdEQQhMB+CC2JvbHR5LmxvY2FshwR/AAABhwTAqAQBhwTAqAEBMB0GA1Ud
DgQWBBTZQ4w8lHqDgAdCaLYUY3QLUc+qXjAfBgNVHSMEGDAWgBTfQs9S3oVp7yJ/
8SxGwHLHWqqaEjAKBggqhkjOPQQDAgNIADBFAiEA1wa8HwUkxGnn+afQjnZGIzRd
wvfOzVaDX+5Onfr7R44CIGH2H11VKsW2/g5+LlkWG28rzAqpFoja8QIK/Co9tQz9
-----END CERTIFICATE-----
)BOLTYREST";

static const char REST_SERVER_KEY_PEM[] = R"BOLTYREST(
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIBT6OMLTBU9WZ7hSSxIQlqI9xB9GDS2Iy/K+FVjZg+9coAoGCCqGSM49
AwEHoUQDQgAEjwv+eku/JMzcLJrE7vOp09DFjqv0se4YNUQ+84aVOM/FqXietkCz
wz7/d1Kp5KDaLuhMijLoEhf9PcTCUljEAQ==
-----END EC PRIVATE KEY-----
)BOLTYREST";

#endif
